var hierarchy =
[
    [ "Account", "class_account.html", null ],
    [ "ALLXMLClearTag", "struct_a_l_l_x_m_l_clear_tag.html", null ],
    [ "BTfast", "class_b_tfast.html", null ],
    [ "DataFeed", "class_data_feed.html", [
      [ "HistoricalBarsCSV", "class_historical_bars_c_s_v.html", null ],
      [ "HistoricalBarsSQLite", "class_historical_bars_s_q_lite.html", null ]
    ] ],
    [ "Date", "class_date.html", null ],
    [ "DateTime", "class_date_time.html", null ],
    [ "Event", "class_event.html", null ],
    [ "ExecutionHandler", "class_execution_handler.html", [
      [ "SimulatedExecution", "class_simulated_execution.html", null ]
    ] ],
    [ "fts5_api", "structfts5__api.html", null ],
    [ "fts5_tokenizer", "structfts5__tokenizer.html", null ],
    [ "Fts5ExtensionApi", "struct_fts5_extension_api.html", null ],
    [ "Fts5PhraseIter", "struct_fts5_phrase_iter.html", null ],
    [ "Individual", "class_individual.html", null ],
    [ "Instrument", "class_instrument.html", null ],
    [ "NextToken", "struct_next_token.html", null ],
    [ "Performance", "class_performance.html", null ],
    [ "Population", "class_population.html", null ],
    [ "Position", "class_position.html", null ],
    [ "PositionHandler", "class_position_handler.html", null ],
    [ "PositionSizer", "class_position_sizer.html", null ],
    [ "PriceCollection", "class_price_collection.html", null ],
    [ "SignalHandler", "class_signal_handler.html", null ],
    [ "sqlite3_file", "structsqlite3__file.html", null ],
    [ "sqlite3_index_info::sqlite3_index_constraint", "structsqlite3__index__info_1_1sqlite3__index__constraint.html", null ],
    [ "sqlite3_index_info::sqlite3_index_constraint_usage", "structsqlite3__index__info_1_1sqlite3__index__constraint__usage.html", null ],
    [ "sqlite3_index_info", "structsqlite3__index__info.html", null ],
    [ "sqlite3_index_info::sqlite3_index_orderby", "structsqlite3__index__info_1_1sqlite3__index__orderby.html", null ],
    [ "sqlite3_io_methods", "structsqlite3__io__methods.html", null ],
    [ "sqlite3_mem_methods", "structsqlite3__mem__methods.html", null ],
    [ "sqlite3_module", "structsqlite3__module.html", null ],
    [ "sqlite3_mutex_methods", "structsqlite3__mutex__methods.html", null ],
    [ "sqlite3_pcache_methods", "structsqlite3__pcache__methods.html", null ],
    [ "sqlite3_pcache_methods2", "structsqlite3__pcache__methods2.html", null ],
    [ "sqlite3_pcache_page", "structsqlite3__pcache__page.html", null ],
    [ "sqlite3_rtree_geometry", "structsqlite3__rtree__geometry.html", null ],
    [ "sqlite3_rtree_query_info", "structsqlite3__rtree__query__info.html", null ],
    [ "sqlite3_snapshot", "structsqlite3__snapshot.html", null ],
    [ "sqlite3_vfs", "structsqlite3__vfs.html", null ],
    [ "sqlite3_vtab", "structsqlite3__vtab.html", null ],
    [ "sqlite3_vtab_cursor", "structsqlite3__vtab__cursor.html", null ],
    [ "Strategy", "class_strategy.html", [
      [ "MasterCode", "class_master_code.html", null ],
      [ "NG1", "class_n_g1.html", null ],
      [ "NG2", "class_n_g2.html", null ],
      [ "NG3", "class_n_g3.html", null ],
      [ "NG4", "class_n_g4.html", null ],
      [ "NG5", "class_n_g5.html", null ],
      [ "Template", "class_template.html", null ],
      [ "Test", "class_test.html", null ]
    ] ],
    [ "Time", "class_time.html", null ],
    [ "ToXMLStringTool", "struct_to_x_m_l_string_tool.html", null ],
    [ "Transaction", "class_transaction.html", null ],
    [ "Validation", "class_validation.html", null ],
    [ "XML", "struct_x_m_l.html", null ],
    [ "XMLAttribute", "struct_x_m_l_attribute.html", null ],
    [ "XMLCharacterEntity", "struct_x_m_l_character_entity.html", null ],
    [ "XMLClear", "struct_x_m_l_clear.html", null ],
    [ "XMLNode", "struct_x_m_l_node.html", null ],
    [ "XMLNodeContents", "struct_x_m_l_node_contents.html", null ],
    [ "XMLNode::XMLNodeDataTag", "struct_x_m_l_node_1_1_x_m_l_node_data_tag.html", null ],
    [ "XMLParserBase64Tool", "struct_x_m_l_parser_base64_tool.html", null ],
    [ "XMLResults", "struct_x_m_l_results.html", null ]
];